// Your Pokémon collection for the favorite tournament.
//
// apiName = the numeric Pokémon ID used by PokéAPI
//
// displayName = what the user sees in the tournament
//
// IMPORTANT:
// - "id" is the app's stable internal ID.
// - "apiName" is the PokéAPI ID.
// - Do not change the app "id" values when updating API data.

const POKEMON = [
  // =========================
  // KANTO
  // =========================

  { id: "venusaur", displayName: "Venusaur", apiName: "3" },
  { id: "charizard", displayName: "Charizard", apiName: "6" },
  { id: "blastoise", displayName: "Blastoise", apiName: "9" },
  { id: "butterfree", displayName: "Butterfree", apiName: "12" },
  { id: "beedrill", displayName: "Beedrill", apiName: "15" },
  { id: "pidgeot", displayName: "Pidgeot", apiName: "18" },
  { id: "fearow", displayName: "Fearow", apiName: "22" },
  { id: "arbok", displayName: "Arbok", apiName: "24" },
  { id: "raichu-kanto", displayName: "Raichu", apiName: "26" },
  { id: "sandslash-kanto", displayName: "Sandslash", apiName: "28" },
  { id: "nidoqueen", displayName: "Nidoqueen", apiName: "31" },
  { id: "nidoking", displayName: "Nidoking", apiName: "34" },
  { id: "clefable", displayName: "Clefable", apiName: "36" },
  { id: "ninetales-kanto", displayName: "Ninetales", apiName: "38" },
  { id: "wigglytuff", displayName: "Wigglytuff", apiName: "40" },
  { id: "vileplume", displayName: "Vileplume", apiName: "45" },
  { id: "venomoth", displayName: "Venomoth", apiName: "49" },
  { id: "dugtrio-kanto", displayName: "Dugtrio", apiName: "51" },
  { id: "persian-kanto", displayName: "Persian", apiName: "53" },
  { id: "golduck", displayName: "Golduck", apiName: "55" },
  { id: "arcanine-kanto", displayName: "Arcanine", apiName: "59" },
  { id: "poliwrath", displayName: "Poliwrath", apiName: "62" },
  { id: "alakazam", displayName: "Alakazam", apiName: "65" },
  { id: "machamp", displayName: "Machamp", apiName: "68" },
  { id: "victreebel", displayName: "Victreebel", apiName: "71" },
  { id: "golem-kanto", displayName: "Golem", apiName: "76" },
  { id: "rapidash-kanto", displayName: "Rapidash", apiName: "78" },
  { id: "dewgong", displayName: "Dewgong", apiName: "87" },
  { id: "cloyster", displayName: "Cloyster", apiName: "91" },
  { id: "gengar", displayName: "Gengar", apiName: "94" },
  { id: "exeggutor-kanto", displayName: "Exeggutor", apiName: "103" },
  { id: "marowak-kanto", displayName: "Marowak", apiName: "105" },
  { id: "hitmonlee", displayName: "Hitmonlee", apiName: "106" },
  { id: "hitmonchan", displayName: "Hitmonchan", apiName: "107" },
  { id: "kangaskhan", displayName: "Kangaskhan", apiName: "115" },
  { id: "pinsir", displayName: "Pinsir", apiName: "127" },
  { id: "tauros-kanto", displayName: "Tauros", apiName: "128" },
  { id: "gyarados", displayName: "Gyarados", apiName: "130" },
  { id: "lapras", displayName: "Lapras", apiName: "131" },
  { id: "ditto", displayName: "Ditto", apiName: "132" },
  { id: "vaporeon", displayName: "Vaporeon", apiName: "134" },
  { id: "jolteon", displayName: "Jolteon", apiName: "135" },
  { id: "flareon", displayName: "Flareon", apiName: "136" },
  { id: "omastar", displayName: "Omastar", apiName: "139" },
  { id: "kabutops", displayName: "Kabutops", apiName: "141" },
  { id: "aerodactyl", displayName: "Aerodactyl", apiName: "142" },
  { id: "snorlax", displayName: "Snorlax", apiName: "143" },
  { id: "articuno-kanto", displayName: "Articuno", apiName: "144" },
  { id: "zapdos-kanto", displayName: "Zapdos", apiName: "145" },
  { id: "moltres-kanto", displayName: "Moltres", apiName: "146" },
  { id: "dragonite", displayName: "Dragonite", apiName: "149" },
  { id: "mewtwo", displayName: "Mewtwo", apiName: "150" },
  { id: "mew", displayName: "Mew", apiName: "151" },

  // =========================
  // JOHTO
  // =========================

  { id: "meganium", displayName: "Meganium", apiName: "154" },
  { id: "typhlosion-johto", displayName: "Typhlosion", apiName: "157" },
  { id: "feraligatr", displayName: "Feraligatr", apiName: "160" },
  { id: "furret", displayName: "Furret", apiName: "162" },
  { id: "noctowl", displayName: "Noctowl", apiName: "164" },
  { id: "ariados", displayName: "Ariados", apiName: "168" },
  { id: "crobat", displayName: "Crobat", apiName: "169" },
  { id: "xatu", displayName: "Xatu", apiName: "178" },
  { id: "ampharos", displayName: "Ampharos", apiName: "181" },
  { id: "bellossom", displayName: "Bellossom", apiName: "182" },
  { id: "azumarill", displayName: "Azumarill", apiName: "184" },
  { id: "sudowoodo", displayName: "Sudowoodo", apiName: "185" },
  { id: "politoed", displayName: "Politoed", apiName: "186" },
  { id: "jumpluff", displayName: "Jumpluff", apiName: "189" },
  { id: "sunflora", displayName: "Sunflora", apiName: "192" },
  { id: "quagsire", displayName: "Quagsire", apiName: "195" },
  { id: "espeon", displayName: "Espeon", apiName: "196" },
  { id: "umbreon", displayName: "Umbreon", apiName: "197" },
  { id: "slowking", displayName: "Slowking", apiName: "199" },
  { id: "unown", displayName: "Unown", apiName: "201" },
  { id: "steelix", displayName: "Steelix", apiName: "208" },
  { id: "granbull", displayName: "Granbull", apiName: "210" },
  { id: "scizor", displayName: "Scizor", apiName: "212" },
  { id: "shuckle", displayName: "Shuckle", apiName: "213" },
  { id: "heracross", displayName: "Heracross", apiName: "214" },
  { id: "mantine", displayName: "Mantine", apiName: "226" },
  { id: "skarmory", displayName: "Skarmory", apiName: "227" },
  { id: "houndoom", displayName: "Houndoom", apiName: "229" },
  { id: "kingdra", displayName: "Kingdra", apiName: "230" },
  { id: "donphan", displayName: "Donphan", apiName: "232" },
  { id: "miltank", displayName: "Miltank", apiName: "241" },
  { id: "blissey", displayName: "Blissey", apiName: "242" },
  { id: "raikou", displayName: "Raikou", apiName: "243" },
  { id: "entei", displayName: "Entei", apiName: "244" },
  { id: "suicune", displayName: "Suicune", apiName: "245" },
  { id: "tyranitar", displayName: "Tyranitar", apiName: "248" },
  { id: "lugia", displayName: "Lugia", apiName: "249" },
  { id: "ho-oh", displayName: "Ho-Oh", apiName: "250" },
  { id: "celebi", displayName: "Celebi", apiName: "251" },

  // =========================
  // HOENN
  // =========================

  { id: "sceptile", displayName: "Sceptile", apiName: "254" },
  { id: "blaziken", displayName: "Blaziken", apiName: "257" },
  { id: "swampert", displayName: "Swampert", apiName: "260" },
  { id: "mightyena", displayName: "Mightyena", apiName: "262" },
  { id: "linoone-hoenn", displayName: "Linoone", apiName: "264" },
  { id: "beautifly", displayName: "Beautifly", apiName: "267" },
  { id: "dustox", displayName: "Dustox", apiName: "269" },
  { id: "ludicolo", displayName: "Ludicolo", apiName: "272" },
  { id: "shiftry", displayName: "Shiftry", apiName: "275" },
  { id: "swellow", displayName: "Swellow", apiName: "277" },
  { id: "pelipper", displayName: "Pelipper", apiName: "279" },
  { id: "gardevoir", displayName: "Gardevoir", apiName: "282" },
  { id: "masquerain", displayName: "Masquerain", apiName: "284" },
  { id: "breloom", displayName: "Breloom", apiName: "286" },
  { id: "slaking", displayName: "Slaking", apiName: "289" },
  { id: "shedinja", displayName: "Shedinja", apiName: "292" },
  { id: "hariyama", displayName: "Hariyama", apiName: "297" },
  { id: "delcatty", displayName: "Delcatty", apiName: "301" },
  { id: "sableye", displayName: "Sableye", apiName: "302" },
  { id: "mawile", displayName: "Mawile", apiName: "303" },
  { id: "aggron", displayName: "Aggron", apiName: "306" },
  { id: "medicham", displayName: "Medicham", apiName: "308" },
  { id: "manectric", displayName: "Manectric", apiName: "310" },
  { id: "sharpedo", displayName: "Sharpedo", apiName: "319" },
  { id: "wailord", displayName: "Wailord", apiName: "321" },
  { id: "camerupt", displayName: "Camerupt", apiName: "323" },
  { id: "torkoal", displayName: "Torkoal", apiName: "324" },
  { id: "flygon", displayName: "Flygon", apiName: "330" },
  { id: "altaria", displayName: "Altaria", apiName: "334" },
  { id: "seviper", displayName: "Seviper", apiName: "336" },
  { id: "whiscash", displayName: "Whiscash", apiName: "340" },
  { id: "claydol", displayName: "Claydol", apiName: "344" },
  { id: "cradily", displayName: "Cradily", apiName: "345" },
  { id: "armaldo", displayName: "Armaldo", apiName: "348" },
  { id: "milotic", displayName: "Milotic", apiName: "350" },
  { id: "castform", displayName: "Castform", apiName: "351" },
  { id: "kecleon", displayName: "Kecleon", apiName: "352" },
  { id: "banette", displayName: "Banette", apiName: "354" },
  { id: "tropius", displayName: "Tropius", apiName: "357" },
  { id: "chimecho", displayName: "Chimecho", apiName: "358" },
  { id: "absol", displayName: "Absol", apiName: "359" },
  { id: "glalie", displayName: "Glalie", apiName: "362" },
  { id: "walrein", displayName: "Walrein", apiName: "365" },
  { id: "relicanth", displayName: "Relicanth", apiName: "369" },
  { id: "salamence", displayName: "Salamence", apiName: "373" },
  { id: "metagross", displayName: "Metagross", apiName: "376" },
  { id: "regirock", displayName: "Regirock", apiName: "377" },
  { id: "regice", displayName: "Regice", apiName: "378" },
  { id: "registeel", displayName: "Registeel", apiName: "379" },
  { id: "latias", displayName: "Latias", apiName: "380" },
  { id: "latios", displayName: "Latios", apiName: "381" },
  { id: "kyogre", displayName: "Kyogre", apiName: "382" },
  { id: "groudon", displayName: "Groudon", apiName: "383" },
  { id: "rayquaza", displayName: "Rayquaza", apiName: "384" },
  { id: "jirachi", displayName: "Jirachi", apiName: "385" },
  { id: "deoxys", displayName: "Deoxys", apiName: "386" },

  // =========================
  // SINNOH
  // =========================

  { id: "torterra", displayName: "Torterra", apiName: "389" },
  { id: "infernape", displayName: "Infernape", apiName: "392" },
  { id: "empoleon", displayName: "Empoleon", apiName: "395" },
  { id: "staraptor", displayName: "Staraptor", apiName: "398" },
  { id: "bibarel", displayName: "Bibarel", apiName: "400" },
  { id: "kricketune", displayName: "Kricketune", apiName: "402" },
  { id: "luxray", displayName: "Luxray", apiName: "405" },
  { id: "roserade", displayName: "Roserade", apiName: "407" },
  { id: "rampardos", displayName: "Rampardos", apiName: "409" },
  { id: "bastiodon", displayName: "Bastiodon", apiName: "411" },
  { id: "vespiquen", displayName: "Vespiquen", apiName: "416" },
  { id: "pachirisu", displayName: "Pachirisu", apiName: "417" },
  { id: "floatzel", displayName: "Floatzel", apiName: "419" },
  { id: "gastrodon", displayName: "Gastrodon", apiName: "423" },
  { id: "ambipom", displayName: "Ambipom", apiName: "424" },
  { id: "drifblim", displayName: "Drifblim", apiName: "426" },
  { id: "lopunny", displayName: "Lopunny", apiName: "428" },
  { id: "mismagius", displayName: "Mismagius", apiName: "429" },
  { id: "honchkrow", displayName: "Honchkrow", apiName: "430" },
  { id: "bronzong", displayName: "Bronzong", apiName: "437" },
  { id: "spiritomb", displayName: "Spiritomb", apiName: "442" },
  { id: "garchomp", displayName: "Garchomp", apiName: "445" },
  { id: "lucario", displayName: "Lucario", apiName: "448" },
  { id: "hippowdon", displayName: "Hippowdon", apiName: "450" },
  { id: "drapion", displayName: "Drapion", apiName: "452" },
  { id: "toxicroak", displayName: "Toxicroak", apiName: "453" },
  { id: "lumineon", displayName: "Lumineon", apiName: "457" },
  { id: "abomasnow", displayName: "Abomasnow", apiName: "460" },
  { id: "weavile", displayName: "Weavile", apiName: "461" },
  { id: "magnezone", displayName: "Magnezone", apiName: "462" },
  { id: "rhyperior", displayName: "Rhyperior", apiName: "464" },
  { id: "tangrowth", displayName: "Tangrowth", apiName: "465" },
  { id: "electivire", displayName: "Electivire", apiName: "466" },
  { id: "magmortar", displayName: "Magmortar", apiName: "467" },
  { id: "togekiss", displayName: "Togekiss", apiName: "468" },
  { id: "yanmega", displayName: "Yanmega", apiName: "469" },
  { id: "leafeon", displayName: "Leafeon", apiName: "470" },
  { id: "glaceon", displayName: "Glaceon", apiName: "471" },
  { id: "gliscor", displayName: "Gliscor", apiName: "472" },
  { id: "mamoswine", displayName: "Mamoswine", apiName: "473" },
  { id: "porygon-z", displayName: "Porygon-Z", apiName: "474" },
  { id: "gallade", displayName: "Gallade", apiName: "475" },
  { id: "probopass", displayName: "Probopass", apiName: "476" },
  { id: "dusknoir", displayName: "Dusknoir", apiName: "477" },
  { id: "froslass", displayName: "Froslass", apiName: "478" },
  { id: "rotom", displayName: "Rotom", apiName: "479" },
  { id: "uxie", displayName: "Uxie", apiName: "480" },
  { id: "mesprit", displayName: "Mesprit", apiName: "481" },
  { id: "azelf", displayName: "Azelf", apiName: "482" },
  { id: "dialga", displayName: "Dialga", apiName: "483" },
  { id: "palkia", displayName: "Palkia", apiName: "484" },
  { id: "heatran", displayName: "Heatran", apiName: "485" },
  { id: "regigigas", displayName: "Regigigas", apiName: "486" },
  { id: "giratina", displayName: "Giratina", apiName: "487" },
  { id: "cresselia", displayName: "Cresselia", apiName: "488" },
  { id: "manaphy", displayName: "Manaphy", apiName: "490" },
  { id: "darkrai", displayName: "Darkrai", apiName: "491" },
  { id: "shaymin", displayName: "Shaymin", apiName: "492" },
  { id: "arceus", displayName: "Arceus", apiName: "493" },

  // =========================
  // UNOVA
  // =========================

  { id: "victini", displayName: "Victini", apiName: "494" },
  { id: "serperior", displayName: "Serperior", apiName: "497" },
  { id: "emboar", displayName: "Emboar", apiName: "500" },
  { id: "samurott-unova", displayName: "Samurott", apiName: "503" },
  { id: "watchog", displayName: "Watchog", apiName: "505" },
  { id: "stoutland", displayName: "Stoutland", apiName: "508" },
  { id: "liepard", displayName: "Liepard", apiName: "510" },
  { id: "musharna", displayName: "Musharna", apiName: "518" },
  { id: "unfezant", displayName: "Unfezant", apiName: "521" },
  { id: "zebstrika", displayName: "Zebstrika", apiName: "523" },
  { id: "gigalith", displayName: "Gigalith", apiName: "526" },
  { id: "swoobat", displayName: "Swoobat", apiName: "528" },
  { id: "excadrill", displayName: "Excadrill", apiName: "530" },
  { id: "audino", displayName: "Audino", apiName: "531" },
  { id: "leavanny", displayName: "Leavanny", apiName: "542" },
  { id: "scolipede", displayName: "Scolipede", apiName: "545" },
  { id: "whimsicott", displayName: "Whimsicott", apiName: "547" },
  { id: "lilligant-unova", displayName: "Lilligant", apiName: "549" },
  { id: "krookodile", displayName: "Krookodile", apiName: "553" },
  { id: "darmanitan-unova", displayName: "Darmanitan", apiName: "555" },
  { id: "sigilyph", displayName: "Sigilyph", apiName: "561" },
  { id: "cofagrigus", displayName: "Cofagrigus", apiName: "563" },
  { id: "carracosta", displayName: "Carracosta", apiName: "565" },
  { id: "archeops", displayName: "Archeops", apiName: "567" },
  { id: "zoroark-unova", displayName: "Zoroark", apiName: "571" },
  { id: "cinccino", displayName: "Cinccino", apiName: "573" },
  { id: "gothitelle", displayName: "Gothitelle", apiName: "576" },
  { id: "reuniclus", displayName: "Reuniclus", apiName: "579" },
  { id: "sawsbuck", displayName: "Sawsbuck", apiName: "586" },
  { id: "emolga", displayName: "Emolga", apiName: "587" },
  { id: "escavalier", displayName: "Escavalier", apiName: "589" },
  { id: "galvantula", displayName: "Galvantula", apiName: "596" },
  { id: "ferrothorn", displayName: "Ferrothorn", apiName: "598" },
  { id: "eelektross", displayName: "Eelektross", apiName: "604" },
  { id: "chandelure", displayName: "Chandelure", apiName: "609" },
  { id: "haxorus", displayName: "Haxorus", apiName: "612" },
  { id: "beartic", displayName: "Beartic", apiName: "614" },
  { id: "accelgor", displayName: "Accelgor", apiName: "617" },
  { id: "mienshao", displayName: "Mienshao", apiName: "620" },
  { id: "druddigon", displayName: "Druddigon", apiName: "621" },
  { id: "golurk", displayName: "Golurk", apiName: "623" },
  { id: "bouffalant", displayName: "Bouffalant", apiName: "626" },
  { id: "braviary-unova", displayName: "Braviary", apiName: "628" },
  { id: "mandibuzz", displayName: "Mandibuzz", apiName: "630" },
  { id: "hydreigon", displayName: "Hydreigon", apiName: "635" },
  { id: "volcarona", displayName: "Volcarona", apiName: "637" },
  { id: "cobalion", displayName: "Cobalion", apiName: "638" },
  { id: "terrakion", displayName: "Terrakion", apiName: "639" },
  { id: "virizion", displayName: "Virizion", apiName: "640" },
  { id: "tornadus", displayName: "Tornadus", apiName: "641" },
  { id: "thundurus", displayName: "Thundurus", apiName: "642" },
  { id: "reshiram", displayName: "Reshiram", apiName: "643" },
  { id: "zekrom", displayName: "Zekrom", apiName: "644" },
  { id: "landorus", displayName: "Landorus", apiName: "645" },
  { id: "kyurem", displayName: "Kyurem", apiName: "646" },
  { id: "keldeo", displayName: "Keldeo", apiName: "647" },

  // =========================
  // KALOS
  // =========================

  { id: "chesnaught", displayName: "Chesnaught", apiName: "652" },
  { id: "delphox", displayName: "Delphox", apiName: "655" },
  { id: "greninja", displayName: "Greninja", apiName: "658" },
  { id: "diggersby", displayName: "Diggersby", apiName: "660" },
  { id: "talonflame", displayName: "Talonflame", apiName: "663" },
  { id: "vivillon", displayName: "Vivillon", apiName: "666" },
  { id: "pyroar", displayName: "Pyroar", apiName: "668" },
  { id: "florges", displayName: "Florges", apiName: "671" },
  { id: "gogoat", displayName: "Gogoat", apiName: "673" },
  { id: "pangoro", displayName: "Pangoro", apiName: "675" },
  { id: "furfrou", displayName: "Furfrou", apiName: "676" },
  { id: "meowstic", displayName: "Meowstic", apiName: "678" },
  { id: "aegislash", displayName: "Aegislash", apiName: "681" },
  { id: "aromatisse", displayName: "Aromatisse", apiName: "683" },
  { id: "malamar", displayName: "Malamar", apiName: "687" },
  { id: "dragalge", displayName: "Dragalge", apiName: "690" },
  { id: "clawitzer", displayName: "Clawitzer", apiName: "693" },
  { id: "heliolisk", displayName: "Heliolisk", apiName: "695" },
  { id: "tyrantrum", displayName: "Tyrantrum", apiName: "697" },
  { id: "aurorus", displayName: "Aurorus", apiName: "699" },
  { id: "sylveon", displayName: "Sylveon", apiName: "700" },
  { id: "hawlucha", displayName: "Hawlucha", apiName: "701" },
  { id: "dedenne", displayName: "Dedenne", apiName: "702" },
  { id: "goodra-kalos", displayName: "Goodra", apiName: "706" },
  { id: "klefki", displayName: "Klefki", apiName: "707" },
  { id: "trevenant", displayName: "Trevenant", apiName: "709" },
  { id: "gourgeist", displayName: "Gourgeist", apiName: "711" },
  { id: "avalugg-kalos", displayName: "Avalugg", apiName: "713" },
  { id: "noivern", displayName: "Noivern", apiName: "715" },
  { id: "xerneas", displayName: "Xerneas", apiName: "716" },
  { id: "yveltal", displayName: "Yveltal", apiName: "717" },
  { id: "zygarde", displayName: "Zygarde", apiName: "718" },
  { id: "diancie", displayName: "Diancie", apiName: "719" },
  { id: "hoopa", displayName: "Hoopa", apiName: "720" },
  { id: "volcanion", displayName: "Volcanion", apiName: "721" },

  // =========================
  // ALOLA
  // =========================

  { id: "decidueye-alola", displayName: "Decidueye", apiName: "724" },
  { id: "incineroar", displayName: "Incineroar", apiName: "727" },
  { id: "primarina", displayName: "Primarina", apiName: "730" },
  { id: "toucannon", displayName: "Toucannon", apiName: "733" },
  { id: "gumshoos", displayName: "Gumshoos", apiName: "735" },

  { id: "raticate-alola", displayName: "Alolan Raticate", apiName: "10092" },
  { id: "raichu-alola", displayName: "Alolan Raichu", apiName: "10100" },

  { id: "vikavolt", displayName: "Vikavolt", apiName: "738" },

  { id: "persian-alola", displayName: "Alolan Persian", apiName: "10108" },
  { id: "muk-alola", displayName: "Alolan Muk", apiName: "10113" },
  { id: "dugtrio-alola", displayName: "Alolan Dugtrio", apiName: "10106" },

  { id: "oricorio", displayName: "Oricorio", apiName: "741" },
  { id: "ribombee", displayName: "Ribombee", apiName: "743" },
  { id: "lycanroc", displayName: "Lycanroc", apiName: "745" },
  { id: "toxapex", displayName: "Toxapex", apiName: "748" },
  { id: "mudsdale", displayName: "Mudsdale", apiName: "750" },
  { id: "araquanid", displayName: "Araquanid", apiName: "752" },
  { id: "lurantis", displayName: "Lurantis", apiName: "754" },
  { id: "shiinotic", displayName: "Shiinotic", apiName: "756" },
  { id: "salazzle", displayName: "Salazzle", apiName: "758" },

  { id: "marowak-alola", displayName: "Alolan Marowak", apiName: "10115" },

  { id: "bewear", displayName: "Bewear", apiName: "760" },
  { id: "tsareena", displayName: "Tsareena", apiName: "763" },
  { id: "comfey", displayName: "Comfey", apiName: "764" },
  { id: "oranguru", displayName: "Oranguru", apiName: "765" },
  { id: "passimian", displayName: "Passimian", apiName: "766" },
  { id: "golisopod", displayName: "Golisopod", apiName: "768" },
  { id: "palossand", displayName: "Palossand", apiName: "770" },
  { id: "pyukumuku", displayName: "Pyukumuku", apiName: "771" },
  { id: "silvally", displayName: "Silvally", apiName: "773" },
  { id: "minior", displayName: "Minior", apiName: "774" },
  { id: "komala", displayName: "Komala", apiName: "775" },
  { id: "turtonator", displayName: "Turtonator", apiName: "776" },
  { id: "togedemaru", displayName: "Togedemaru", apiName: "777" },

  { id: "golem-alola", displayName: "Alolan Golem", apiName: "10111" },

  { id: "mimikyu", displayName: "Mimikyu", apiName: "778" },
  { id: "bruxish", displayName: "Bruxish", apiName: "779" },
  { id: "drampa", displayName: "Drampa", apiName: "780" },

  { id: "sandslash-alola", displayName: "Alolan Sandslash", apiName: "10102" },
  { id: "ninetales-alola", displayName: "Alolan Ninetales", apiName: "10104" },

  { id: "dhelmise", displayName: "Dhelmise", apiName: "781" },

  { id: "exeggutor-alola", displayName: "Alolan Exeggutor", apiName: "10114" },

  { id: "kommo-o", displayName: "Kommo-o", apiName: "784" },
  { id: "tapu-koko", displayName: "Tapu Koko", apiName: "785" },
  { id: "tapu-lele", displayName: "Tapu Lele", apiName: "786" },
  { id: "tapu-bulu", displayName: "Tapu Bulu", apiName: "787" },
  { id: "tapu-fini", displayName: "Tapu Fini", apiName: "788" },
  { id: "solgaleo", displayName: "Solgaleo", apiName: "791" },
  { id: "lunala", displayName: "Lunala", apiName: "792" },
  { id: "nihilego", displayName: "Nihilego", apiName: "793" },
  { id: "buzzwole", displayName: "Buzzwole", apiName: "794" },
  { id: "pheromosa", displayName: "Pheromosa", apiName: "795" },
  { id: "xurkitree", displayName: "Xurkitree", apiName: "796" },
  { id: "celesteela", displayName: "Celesteela", apiName: "797" },
  { id: "kartana", displayName: "Kartana", apiName: "798" },
  { id: "guzzlord", displayName: "Guzzlord", apiName: "799" },
  { id: "necrozma", displayName: "Necrozma", apiName: "800" },
  { id: "magearna", displayName: "Magearna", apiName: "801" },
  { id: "marshadow", displayName: "Marshadow", apiName: "802" },
  { id: "naganadel", displayName: "Naganadel", apiName: "804" },
  { id: "stakataka", displayName: "Stakataka", apiName: "805" },
  { id: "blacephalon", displayName: "Blacephalon", apiName: "806" },
  { id: "zeraora", displayName: "Zeraora", apiName: "807" },
  { id: "melmetal", displayName: "Melmetal", apiName: "809" },
];
