// Your Pokémon collection for the favorite tournament.
// apiName = the exact Pokémon name used by PokéAPI
// displayName = what the user sees in the tournament

const POKEMON = [
  // =========================
  // KANTO
  // =========================

  { id: "venusaur", displayName: "Venusaur", apiName: "venusaur" },
  { id: "charizard", displayName: "Charizard", apiName: "charizard" },
  { id: "blastoise", displayName: "Blastoise", apiName: "blastoise" },
  { id: "butterfree", displayName: "Butterfree", apiName: "butterfree" },
  { id: "beedrill", displayName: "Beedrill", apiName: "beedrill" },
  { id: "pidgeot", displayName: "Pidgeot", apiName: "pidgeot" },
  { id: "fearow", displayName: "Fearow", apiName: "fearow" },
  { id: "arbok", displayName: "Arbok", apiName: "arbok" },
  { id: "raichu-kanto", displayName: "Raichu", apiName: "raichu" },
  { id: "sandslash-kanto", displayName: "Sandslash", apiName: "sandslash" },
  { id: "nidoqueen", displayName: "Nidoqueen", apiName: "nidoqueen" },
  { id: "nidoking", displayName: "Nidoking", apiName: "nidoking" },
  { id: "clefable", displayName: "Clefable", apiName: "clefable" },
  { id: "ninetales-kanto", displayName: "Ninetales", apiName: "ninetales" },
  { id: "wigglytuff", displayName: "Wigglytuff", apiName: "wigglytuff" },
  { id: "vileplume", displayName: "Vileplume", apiName: "vileplume" },
  { id: "venomoth", displayName: "Venomoth", apiName: "venomoth" },
  { id: "dugtrio-kanto", displayName: "Dugtrio", apiName: "dugtrio" },
  { id: "persian-kanto", displayName: "Persian", apiName: "persian" },
  { id: "golduck", displayName: "Golduck", apiName: "golduck" },
  { id: "arcanine-kanto", displayName: "Arcanine", apiName: "arcanine" },
  { id: "poliwrath", displayName: "Poliwrath", apiName: "poliwrath" },
  { id: "alakazam", displayName: "Alakazam", apiName: "alakazam" },
  { id: "machamp", displayName: "Machamp", apiName: "machamp" },
  { id: "victreebel", displayName: "Victreebel", apiName: "victreebel" },
  { id: "golem-kanto", displayName: "Golem", apiName: "golem" },
  { id: "rapidash-kanto", displayName: "Rapidash", apiName: "rapidash" },
  { id: "dewgong", displayName: "Dewgong", apiName: "dewgong" },
  { id: "cloyster", displayName: "Cloyster", apiName: "cloyster" },
  { id: "gengar", displayName: "Gengar", apiName: "gengar" },
  { id: "exeggutor-kanto", displayName: "Exeggutor", apiName: "exeggutor" },
  { id: "marowak-kanto", displayName: "Marowak", apiName: "marowak" },
  { id: "hitmonlee", displayName: "Hitmonlee", apiName: "hitmonlee" },
  { id: "hitmonchan", displayName: "Hitmonchan", apiName: "hitmonchan" },
  { id: "kangaskhan", displayName: "Kangaskhan", apiName: "kangaskhan" },
  { id: "pinsir", displayName: "Pinsir", apiName: "pinsir" },
  { id: "tauros-kanto", displayName: "Tauros", apiName: "tauros" },
  { id: "gyarados", displayName: "Gyarados", apiName: "gyarados" },
  { id: "lapras", displayName: "Lapras", apiName: "lapras" },
  { id: "ditto", displayName: "Ditto", apiName: "ditto" },
  { id: "vaporeon", displayName: "Vaporeon", apiName: "vaporeon" },
  { id: "jolteon", displayName: "Jolteon", apiName: "jolteon" },
  { id: "flareon", displayName: "Flareon", apiName: "flareon" },
  { id: "omastar", displayName: "Omastar", apiName: "omastar" },
  { id: "kabutops", displayName: "Kabutops", apiName: "kabutops" },
  { id: "aerodactyl", displayName: "Aerodactyl", apiName: "aerodactyl" },
  { id: "snorlax", displayName: "Snorlax", apiName: "snorlax" },
  { id: "articuno-kanto", displayName: "Articuno", apiName: "articuno" },
  { id: "zapdos-kanto", displayName: "Zapdos", apiName: "zapdos" },
  { id: "moltres-kanto", displayName: "Moltres", apiName: "moltres" },
  { id: "dragonite", displayName: "Dragonite", apiName: "dragonite" },
  { id: "mewtwo", displayName: "Mewtwo", apiName: "mewtwo" },
  { id: "mew", displayName: "Mew", apiName: "mew" },

  // =========================
  // JOHTO
  // =========================

  { id: "meganium", displayName: "Meganium", apiName: "meganium" },
  { id: "typhlosion-johto", displayName: "Typhlosion", apiName: "typhlosion" },
  { id: "feraligatr", displayName: "Feraligatr", apiName: "feraligatr" },
  { id: "furret", displayName: "Furret", apiName: "furret" },
  { id: "noctowl", displayName: "Noctowl", apiName: "noctowl" },
  { id: "ariados", displayName: "Ariados", apiName: "ariados" },
  { id: "crobat", displayName: "Crobat", apiName: "crobat" },
  { id: "xatu", displayName: "Xatu", apiName: "xatu" },
  { id: "ampharos", displayName: "Ampharos", apiName: "ampharos" },
  { id: "bellossom", displayName: "Bellossom", apiName: "bellossom" },
  { id: "azumarill", displayName: "Azumarill", apiName: "azumarill" },
  { id: "sudowoodo", displayName: "Sudowoodo", apiName: "sudowoodo" },
  { id: "politoed", displayName: "Politoed", apiName: "politoed" },
  { id: "jumpluff", displayName: "Jumpluff", apiName: "jumpluff" },
  { id: "sunflora", displayName: "Sunflora", apiName: "sunflora" },
  { id: "quagsire", displayName: "Quagsire", apiName: "quagsire" },
  { id: "espeon", displayName: "Espeon", apiName: "espeon" },
  { id: "umbreon", displayName: "Umbreon", apiName: "umbreon" },
  { id: "slowking", displayName: "Slowking", apiName: "slowking" },
  { id: "unown", displayName: "Unown", apiName: "unown" },
  { id: "steelix", displayName: "Steelix", apiName: "steelix" },
  { id: "granbull", displayName: "Granbull", apiName: "granbull" },
  { id: "scizor", displayName: "Scizor", apiName: "scizor" },
  { id: "shuckle", displayName: "Shuckle", apiName: "shuckle" },
  { id: "heracross", displayName: "Heracross", apiName: "heracross" },
  { id: "mantine", displayName: "Mantine", apiName: "mantine" },
  { id: "skarmory", displayName: "Skarmory", apiName: "skarmory" },
  { id: "houndoom", displayName: "Houndoom", apiName: "houndoom" },
  { id: "kingdra", displayName: "Kingdra", apiName: "kingdra" },
  { id: "donphan", displayName: "Donphan", apiName: "donphan" },
  { id: "miltank", displayName: "Miltank", apiName: "miltank" },
  { id: "blissey", displayName: "Blissey", apiName: "blissey" },
  { id: "raikou", displayName: "Raikou", apiName: "raikou" },
  { id: "entei", displayName: "Entei", apiName: "entei" },
  { id: "suicune", displayName: "Suicune", apiName: "suicune" },
  { id: "tyranitar", displayName: "Tyranitar", apiName: "tyranitar" },
  { id: "lugia", displayName: "Lugia", apiName: "lugia" },
  { id: "ho-oh", displayName: "Ho-Oh", apiName: "ho-oh" },
  { id: "celebi", displayName: "Celebi", apiName: "celebi" },

  // =========================
  // HOENN
  // =========================

  { id: "sceptile", displayName: "Sceptile", apiName: "sceptile" },
  { id: "blaziken", displayName: "Blaziken", apiName: "blaziken" },
  { id: "swampert", displayName: "Swampert", apiName: "swampert" },
  { id: "mightyena", displayName: "Mightyena", apiName: "mightyena" },
  { id: "linoone-hoenn", displayName: "Linoone", apiName: "linoone" },
  { id: "beautifly", displayName: "Beautifly", apiName: "beautifly" },
  { id: "dustox", displayName: "Dustox", apiName: "dustox" },
  { id: "ludicolo", displayName: "Ludicolo", apiName: "ludicolo" },
  { id: "shiftry", displayName: "Shiftry", apiName: "shiftry" },
  { id: "swellow", displayName: "Swellow", apiName: "swellow" },
  { id: "pelipper", displayName: "Pelipper", apiName: "pelipper" },
  { id: "gardevoir", displayName: "Gardevoir", apiName: "gardevoir" },
  { id: "masquerain", displayName: "Masquerain", apiName: "masquerain" },
  { id: "breloom", displayName: "Breloom", apiName: "breloom" },
  { id: "slaking", displayName: "Slaking", apiName: "slaking" },
  { id: "shedinja", displayName: "Shedinja", apiName: "shedinja" },
  { id: "hariyama", displayName: "Hariyama", apiName: "hariyama" },
  { id: "delcatty", displayName: "Delcatty", apiName: "delcatty" },
  { id: "sableye", displayName: "Sableye", apiName: "sableye" },
  { id: "mawile", displayName: "Mawile", apiName: "mawile" },
  { id: "aggron", displayName: "Aggron", apiName: "aggron" },
  { id: "medicham", displayName: "Medicham", apiName: "medicham" },
  { id: "manectric", displayName: "Manectric", apiName: "manectric" },
  { id: "sharpedo", displayName: "Sharpedo", apiName: "sharpedo" },
  { id: "wailord", displayName: "Wailord", apiName: "wailord" },
  { id: "camerupt", displayName: "Camerupt", apiName: "camerupt" },
  { id: "torkoal", displayName: "Torkoal", apiName: "torkoal" },
  { id: "flygon", displayName: "Flygon", apiName: "flygon" },
  { id: "altaria", displayName: "Altaria", apiName: "altaria" },
  { id: "seviper", displayName: "Seviper", apiName: "seviper" },
  { id: "whiscash", displayName: "Whiscash", apiName: "whiscash" },
  { id: "claydol", displayName: "Claydol", apiName: "claydol" },
  { id: "cradily", displayName: "Cradily", apiName: "cradily" },
  { id: "armaldo", displayName: "Armaldo", apiName: "armaldo" },
  { id: "milotic", displayName: "Milotic", apiName: "milotic" },
  { id: "castform", displayName: "Castform", apiName: "castform" },
  { id: "kecleon", displayName: "Kecleon", apiName: "kecleon" },
  { id: "banette", displayName: "Banette", apiName: "banette" },
  { id: "tropius", displayName: "Tropius", apiName: "tropius" },
  { id: "chimecho", displayName: "Chimecho", apiName: "chimecho" },
  { id: "absol", displayName: "Absol", apiName: "absol" },
  { id: "glalie", displayName: "Glalie", apiName: "glalie" },
  { id: "walrein", displayName: "Walrein", apiName: "walrein" },
  { id: "relicanth", displayName: "Relicanth", apiName: "relicanth" },
  { id: "salamence", displayName: "Salamence", apiName: "salamence" },
  { id: "metagross", displayName: "Metagross", apiName: "metagross" },
  { id: "regirock", displayName: "Regirock", apiName: "regirock" },
  { id: "regice", displayName: "Regice", apiName: "regice" },
  { id: "registeel", displayName: "Registeel", apiName: "registeel" },
  { id: "latias", displayName: "Latias", apiName: "latias" },
  { id: "latios", displayName: "Latios", apiName: "latios" },
  { id: "kyogre", displayName: "Kyogre", apiName: "kyogre" },
  { id: "groudon", displayName: "Groudon", apiName: "groudon" },
  { id: "rayquaza", displayName: "Rayquaza", apiName: "rayquaza" },
  { id: "jirachi", displayName: "Jirachi", apiName: "jirachi" },
  { id: "deoxys", displayName: "Deoxys", apiName: "deoxys" },

  // =========================
  // SINNOH
  // =========================

  { id: "torterra", displayName: "Torterra", apiName: "torterra" },
  { id: "infernape", displayName: "Infernape", apiName: "infernape" },
  { id: "empoleon", displayName: "Empoleon", apiName: "empoleon" },
  { id: "staraptor", displayName: "Staraptor", apiName: "staraptor" },
  { id: "bibarel", displayName: "Bibarel", apiName: "bibarel" },
  { id: "kricketune", displayName: "Kricketune", apiName: "kricketune" },
  { id: "luxray", displayName: "Luxray", apiName: "luxray" },
  { id: "roserade", displayName: "Roserade", apiName: "roserade" },
  { id: "rampardos", displayName: "Rampardos", apiName: "rampardos" },
  { id: "bastiodon", displayName: "Bastiodon", apiName: "bastiodon" },
  { id: "vespiquen", displayName: "Vespiquen", apiName: "vespiquen" },
  { id: "pachirisu", displayName: "Pachirisu", apiName: "pachirisu" },
  { id: "floatzel", displayName: "Floatzel", apiName: "floatzel" },
  { id: "gastrodon", displayName: "Gastrodon", apiName: "gastrodon" },
  { id: "ambipom", displayName: "Ambipom", apiName: "ambipom" },
  { id: "drifblim", displayName: "Drifblim", apiName: "drifblim" },
  { id: "lopunny", displayName: "Lopunny", apiName: "lopunny" },
  { id: "mismagius", displayName: "Mismagius", apiName: "mismagius" },
  { id: "honchkrow", displayName: "Honchkrow", apiName: "honchkrow" },
  { id: "bronzong", displayName: "Bronzong", apiName: "bronzong" },
  { id: "spiritomb", displayName: "Spiritomb", apiName: "spiritomb" },
  { id: "garchomp", displayName: "Garchomp", apiName: "garchomp" },
  { id: "lucario", displayName: "Lucario", apiName: "lucario" },
  { id: "hippowdon", displayName: "Hippowdon", apiName: "hippowdon" },
  { id: "drapion", displayName: "Drapion", apiName: "drapion" },
  { id: "toxicroak", displayName: "Toxicroak", apiName: "toxicroak" },
  { id: "lumineon", displayName: "Lumineon", apiName: "lumineon" },
  { id: "abomasnow", displayName: "Abomasnow", apiName: "abomasnow" },
  { id: "weavile", displayName: "Weavile", apiName: "weavile" },
  { id: "magnezone", displayName: "Magnezone", apiName: "magnezone" },
  { id: "rhyperior", displayName: "Rhyperior", apiName: "rhyperior" },
  { id: "tangrowth", displayName: "Tangrowth", apiName: "tangrowth" },
  { id: "electivire", displayName: "Electivire", apiName: "electivire" },
  { id: "magmortar", displayName: "Magmortar", apiName: "magmortar" },
  { id: "togekiss", displayName: "Togekiss", apiName: "togekiss" },
  { id: "yanmega", displayName: "Yanmega", apiName: "yanmega" },
  { id: "leafeon", displayName: "Leafeon", apiName: "leafeon" },
  { id: "glaceon", displayName: "Glaceon", apiName: "glaceon" },
  { id: "gliscor", displayName: "Gliscor", apiName: "gliscor" },
  { id: "mamoswine", displayName: "Mamoswine", apiName: "mamoswine" },
  { id: "porygon-z", displayName: "Porygon-Z", apiName: "porygon-z" },
  { id: "gallade", displayName: "Gallade", apiName: "gallade" },
  { id: "probopass", displayName: "Probopass", apiName: "probopass" },
  { id: "dusknoir", displayName: "Dusknoir", apiName: "dusknoir" },
  { id: "froslass", displayName: "Froslass", apiName: "froslass" },
  { id: "rotom", displayName: "Rotom", apiName: "rotom" },
  { id: "uxie", displayName: "Uxie", apiName: "uxie" },
  { id: "mesprit", displayName: "Mesprit", apiName: "mesprit" },
  { id: "azelf", displayName: "Azelf", apiName: "azelf" },
  { id: "dialga", displayName: "Dialga", apiName: "dialga" },
  { id: "palkia", displayName: "Palkia", apiName: "palkia" },
  { id: "heatran", displayName: "Heatran", apiName: "heatran" },
  { id: "regigigas", displayName: "Regigigas", apiName: "regigigas" },
  { id: "giratina", displayName: "Giratina", apiName: "giratina" },
  { id: "cresselia", displayName: "Cresselia", apiName: "cresselia" },
  { id: "manaphy", displayName: "Manaphy", apiName: "manaphy" },
  { id: "darkrai", displayName: "Darkrai", apiName: "darkrai" },
  { id: "shaymin", displayName: "Shaymin", apiName: "shaymin" },
  { id: "arceus", displayName: "Arceus", apiName: "arceus" },

  // =========================
  // UNOVA
  // =========================

  { id: "victini", displayName: "Victini", apiName: "victini" },
  { id: "serperior", displayName: "Serperior", apiName: "serperior" },
  { id: "emboar", displayName: "Emboar", apiName: "emboar" },
  { id: "samurott-unova", displayName: "Samurott", apiName: "samurott" },
  { id: "watchog", displayName: "Watchog", apiName: "watchog" },
  { id: "stoutland", displayName: "Stoutland", apiName: "stoutland" },
  { id: "liepard", displayName: "Liepard", apiName: "liepard" },
  { id: "musharna", displayName: "Musharna", apiName: "musharna" },
  { id: "unfezant", displayName: "Unfezant", apiName: "unfezant" },
  { id: "zebstrika", displayName: "Zebstrika", apiName: "zebstrika" },
  { id: "gigalith", displayName: "Gigalith", apiName: "gigalith" },
  { id: "swoobat", displayName: "Swoobat", apiName: "swoobat" },
  { id: "excadrill", displayName: "Excadrill", apiName: "excadrill" },
  { id: "audino", displayName: "Audino", apiName: "audino" },
  { id: "leavanny", displayName: "Leavanny", apiName: "leavanny" },
  { id: "scolipede", displayName: "Scolipede", apiName: "scolipede" },
  { id: "whimsicott", displayName: "Whimsicott", apiName: "whimsicott" },
  { id: "lilligant-unova", displayName: "Lilligant", apiName: "lilligant" },
  { id: "krookodile", displayName: "Krookodile", apiName: "krookodile" },
  { id: "darmanitan-unova", displayName: "Darmanitan", apiName: "darmanitan" },
  { id: "sigilyph", displayName: "Sigilyph", apiName: "sigilyph" },
  { id: "cofagrigus", displayName: "Cofagrigus", apiName: "cofagrigus" },
  { id: "carracosta", displayName: "Carracosta", apiName: "carracosta" },
  { id: "archeops", displayName: "Archeops", apiName: "archeops" },
  { id: "zoroark-unova", displayName: "Zoroark", apiName: "zoroark" },
  { id: "cinccino", displayName: "Cinccino", apiName: "cinccino" },
  { id: "gothitelle", displayName: "Gothitelle", apiName: "gothitelle" },
  { id: "reuniclus", displayName: "Reuniclus", apiName: "reuniclus" },
  { id: "sawsbuck", displayName: "Sawsbuck", apiName: "sawsbuck" },
  { id: "emolga", displayName: "Emolga", apiName: "emolga" },
  { id: "escavalier", displayName: "Escavalier", apiName: "escavalier" },
  { id: "galvantula", displayName: "Galvantula", apiName: "galvantula" },
  { id: "ferrothorn", displayName: "Ferrothorn", apiName: "ferrothorn" },
  { id: "eelektross", displayName: "Eelektross", apiName: "eelektross" },
  { id: "chandelure", displayName: "Chandelure", apiName: "chandelure" },
  { id: "haxorus", displayName: "Haxorus", apiName: "haxorus" },
  { id: "beartic", displayName: "Beartic", apiName: "beartic" },
  { id: "accelgor", displayName: "Accelgor", apiName: "accelgor" },
  { id: "mienshao", displayName: "Mienshao", apiName: "mienshao" },
  { id: "druddigon", displayName: "Druddigon", apiName: "druddigon" },
  { id: "golurk", displayName: "Golurk", apiName: "golurk" },
  { id: "bouffalant", displayName: "Bouffalant", apiName: "bouffalant" },
  { id: "braviary-unova", displayName: "Braviary", apiName: "braviary" },
  { id: "mandibuzz", displayName: "Mandibuzz", apiName: "mandibuzz" },
  { id: "hydreigon", displayName: "Hydreigon", apiName: "hydreigon" },
  { id: "volcarona", displayName: "Volcarona", apiName: "volcarona" },
  { id: "cobalion", displayName: "Cobalion", apiName: "cobalion" },
  { id: "terrakion", displayName: "Terrakion", apiName: "terrakion" },
  { id: "virizion", displayName: "Virizion", apiName: "virizion" },
  { id: "tornadus", displayName: "Tornadus", apiName: "tornadus" },
  { id: "thundurus", displayName: "Thundurus", apiName: "thundurus" },
  { id: "reshiram", displayName: "Reshiram", apiName: "reshiram" },
  { id: "zekrom", displayName: "Zekrom", apiName: "zekrom" },
  { id: "landorus", displayName: "Landorus", apiName: "landorus" },
  { id: "kyurem", displayName: "Kyurem", apiName: "kyurem" },
  { id: "keldeo", displayName: "Keldeo", apiName: "keldeo" },

  // =========================
  // KALOS
  // =========================

  { id: "chesnaught", displayName: "Chesnaught", apiName: "chesnaught" },
  { id: "delphox", displayName: "Delphox", apiName: "delphox" },
  { id: "greninja", displayName: "Greninja", apiName: "greninja" },
  { id: "diggersby", displayName: "Diggersby", apiName: "diggersby" },
  { id: "talonflame", displayName: "Talonflame", apiName: "talonflame" },
  { id: "vivillon", displayName: "Vivillon", apiName: "vivillon" },
  { id: "pyroar", displayName: "Pyroar", apiName: "pyroar" },
  { id: "florges", displayName: "Florges", apiName: "florges" },
  { id: "gogoat", displayName: "Gogoat", apiName: "gogoat" },
  { id: "pangoro", displayName: "Pangoro", apiName: "pangoro" },
  { id: "furfrou", displayName: "Furfrou", apiName: "furfrou" },
  { id: "meowstic", displayName: "Meowstic", apiName: "meowstic" },
  { id: "aegislash", displayName: "Aegislash", apiName: "aegislash" },
  { id: "aromatisse", displayName: "Aromatisse", apiName: "aromatisse" },
  { id: "malamar", displayName: "Malamar", apiName: "malamar" },
  { id: "dragalge", displayName: "Dragalge", apiName: "dragalge" },
  { id: "clawitzer", displayName: "Clawitzer", apiName: "clawitzer" },
  { id: "heliolisk", displayName: "Heliolisk", apiName: "heliolisk" },
  { id: "tyrantrum", displayName: "Tyrantrum", apiName: "tyrantrum" },
  { id: "aurorus", displayName: "Aurorus", apiName: "aurorus" },
  { id: "sylveon", displayName: "Sylveon", apiName: "sylveon" },
  { id: "hawlucha", displayName: "Hawlucha", apiName: "hawlucha" },
  { id: "dedenne", displayName: "Dedenne", apiName: "dedenne" },
  { id: "goodra-kalos", displayName: "Goodra", apiName: "goodra" },
  { id: "klefki", displayName: "Klefki", apiName: "klefki" },
  { id: "trevenant", displayName: "Trevenant", apiName: "trevenant" },
  { id: "gourgeist", displayName: "Gourgeist", apiName: "gourgeist" },
  { id: "avalugg-kalos", displayName: "Avalugg", apiName: "avalugg" },
  { id: "noivern", displayName: "Noivern", apiName: "noivern" },
  { id: "xerneas", displayName: "Xerneas", apiName: "xerneas" },
  { id: "yveltal", displayName: "Yveltal", apiName: "yveltal" },
  { id: "zygarde", displayName: "Zygarde", apiName: "zygarde" },
  { id: "diancie", displayName: "Diancie", apiName: "diancie" },
  { id: "hoopa", displayName: "Hoopa", apiName: "hoopa" },
  { id: "volcanion", displayName: "Volcanion", apiName: "volcanion" },

  // =========================
  // ALOLA
  // =========================

  { id: "decidueye-alola", displayName: "Decidueye", apiName: "decidueye" },
  { id: "incineroar", displayName: "Incineroar", apiName: "incineroar" },
  { id: "primarina", displayName: "Primarina", apiName: "primarina" },
  { id: "toucannon", displayName: "Toucannon", apiName: "toucannon" },
  { id: "gumshoos", displayName: "Gumshoos", apiName: "gumshoos" },
  {
    id: "raticate-alola",
    displayName: "Alolan Raticate",
    apiName: "raticate-alola",
  },
  { id: "raichu-alola", displayName: "Alolan Raichu", apiName: "raichu-alola" },
  { id: "vikavolt", displayName: "Vikavolt", apiName: "vikavolt" },
  {
    id: "persian-alola",
    displayName: "Alolan Persian",
    apiName: "persian-alola",
  },
  { id: "muk-alola", displayName: "Alolan Muk", apiName: "muk-alola" },
  {
    id: "dugtrio-alola",
    displayName: "Alolan Dugtrio",
    apiName: "dugtrio-alola",
  },
  { id: "oricorio", displayName: "Oricorio", apiName: "oricorio" },
  { id: "ribombee", displayName: "Ribombee", apiName: "ribombee" },
  { id: "lycanroc", displayName: "Lycanroc", apiName: "lycanroc" },
  { id: "toxapex", displayName: "Toxapex", apiName: "toxapex" },
  { id: "mudsdale", displayName: "Mudsdale", apiName: "mudsdale" },
  { id: "araquanid", displayName: "Araquanid", apiName: "araquanid" },
  { id: "lurantis", displayName: "Lurantis", apiName: "lurantis" },
  { id: "shiinotic", displayName: "Shiinotic", apiName: "shiinotic" },
  { id: "salazzle", displayName: "Salazzle", apiName: "salazzle" },
  {
    id: "marowak-alola",
    displayName: "Alolan Marowak",
    apiName: "marowak-alola",
  },
  { id: "bewear", displayName: "Bewear", apiName: "bewear" },
  { id: "tsareena", displayName: "Tsareena", apiName: "tsareena" },
  { id: "comfey", displayName: "Comfey", apiName: "comfey" },
  { id: "oranguru", displayName: "Oranguru", apiName: "oranguru" },
  { id: "passimian", displayName: "Passimian", apiName: "passimian" },
  { id: "golisopod", displayName: "Golisopod", apiName: "golisopod" },
  { id: "palossand", displayName: "Palossand", apiName: "palossand" },
  { id: "pyukumuku", displayName: "Pyukumuku", apiName: "pyukumuku" },
  { id: "silvally", displayName: "Silvally", apiName: "silvally" },
  { id: "minior", displayName: "Minior", apiName: "minior" },
  { id: "komala", displayName: "Komala", apiName: "komala" },
  { id: "turtonator", displayName: "Turtonator", apiName: "turtonator" },
  { id: "togedemaru", displayName: "Togedemaru", apiName: "togedemaru" },
  { id: "golem-alola", displayName: "Alolan Golem", apiName: "golem-alola" },
  { id: "mimikyu", displayName: "Mimikyu", apiName: "mimikyu" },
  { id: "bruxish", displayName: "Bruxish", apiName: "bruxish" },
  { id: "drampa", displayName: "Drampa", apiName: "drampa" },
  {
    id: "sandslash-alola",
    displayName: "Alolan Sandslash",
    apiName: "sandslash-alola",
  },
  {
    id: "ninetales-alola",
    displayName: "Alolan Ninetales",
    apiName: "ninetales-alola",
  },
  { id: "dhelmise", displayName: "Dhelmise", apiName: "dhelmise" },
  {
    id: "exeggutor-alola",
    displayName: "Alolan Exeggutor",
    apiName: "exeggutor-alola",
  },
  { id: "kommo-o", displayName: "Kommo-o", apiName: "kommo-o" },
  { id: "tapu-koko", displayName: "Tapu Koko", apiName: "tapu-koko" },
  { id: "tapu-lele", displayName: "Tapu Lele", apiName: "tapu-lele" },
  { id: "tapu-bulu", displayName: "Tapu Bulu", apiName: "tapu-bulu" },
  { id: "tapu-fini", displayName: "Tapu Fini", apiName: "tapu-fini" },
  { id: "solgaleo", displayName: "Solgaleo", apiName: "solgaleo" },
  { id: "lunala", displayName: "Lunala", apiName: "lunala" },
  { id: "nihilego", displayName: "Nihilego", apiName: "nihilego" },
  { id: "buzzwole", displayName: "Buzzwole", apiName: "buzzwole" },
  { id: "pheromosa", displayName: "Pheromosa", apiName: "pheromosa" },
  { id: "xurkitree", displayName: "Xurkitree", apiName: "xurkitree" },
  { id: "celesteela", displayName: "Celesteela", apiName: "celesteela" },
  { id: "kartana", displayName: "Kartana", apiName: "kartana" },
  { id: "guzzlord", displayName: "Guzzlord", apiName: "guzzlord" },
  { id: "necrozma", displayName: "Necrozma", apiName: "necrozma" },
  { id: "magearna", displayName: "Magearna", apiName: "magearna" },
  { id: "marshadow", displayName: "Marshadow", apiName: "marshadow" },
  { id: "naganadel", displayName: "Naganadel", apiName: "naganadel" },
  { id: "stakataka", displayName: "Stakataka", apiName: "stakataka" },
  { id: "blacephalon", displayName: "Blacephalon", apiName: "blacephalon" },
  { id: "zeraora", displayName: "Zeraora", apiName: "zeraora" },
  { id: "melmetal", displayName: "Melmetal", apiName: "melmetal" },
];
